version: '3.8'

services:
  api-server:
    restart: always
    depends_on:
      - mongodb
    build:
      context: .
      target: dev
    ports:
      - 5000:5000
      - 9229:9229
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/db
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./:/app
    networks:
      - chat-app

  mongo:
    image: mongo:4.2.8
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-app

volumes:
  mongo-data:
    driver: local

networks:
  chat-app:
    driver: bridge
