version: '3.8'

services:
  mongodb:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  app:
    depends_on:
      - mongodb
    build:
      context: .
      target: dev
    ports:
      - 5000:5000
      - 9229:9229
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/db
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./:/app
    command: npm run start:debug

volumes:
  mongodb:
  mongodb_config:
